ARG PYTHON_VERSION=3.10.7-slim-bullseye
FROM python:${PYTHON_VERSION}

LABEL author="Carson Sprock <csprock@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# create non-root user
# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME --shell /bin/bash \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

ENV PATH="${PATH}:/home/user/.local/bin"
RUN echo "export PATH=${PATH} >> /home/user/.bashrc"

RUN mkdir -p /app && \
    chown -R $USERNAME:$USER_UID /app
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    g++ \
    gcc \
    git-all \
    make \ 
    software-properties-common \
    unzip \
    vim \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


USER $USERNAME

#install Rust
# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


# install poetry
RUN curl -sSL https://install.python-poetry.org | python -

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt